[enhancement] deprecated init cache in favor of separated repositories
mercadopago/px-android pull request #2425
Opened 2021-02-17 07:37 UTC by cgaggino

2021-02-17 15:11 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/AbstractLocalRepository.kt
> +        value?.let { fileManager.writeToFile(file, it) }
No es non null value?

2021-02-17 15:18 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/AbstractLocalRepository.kt
> +        value?.let { fileManager.writeToFile(file, it) }
No lo sabes en realidad T puede ser "String?"

2021-02-17 15:26 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/AbstractLocalRepository.kt
> +        value?.let { fileManager.writeToFile(file, it) }
Cerrá el portón

2021-02-17 15:27 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PayerComplianceRepositoryImpl.kt
> +    override fun readFromStorage(): PayerCompliance? = fileManager.readParcelable(file, PayerCompliance.CREATOR)
Desestimado

2021-02-17 15:27 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/DiscountServiceImpl.kt
> +class DiscountServiceImpl(private val fileManager: FileManager,
Lo agrego!

2021-02-17 15:28 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/ConfigurationSolverImpl.kt
> +        return payerPaymentMethodRepository.value.firstOrNull { it.id.equals(customOptionId, ignoreCase = true) }
no lo toque mucho porque la idea es que muera cuando cambiemos como buscamos los payer cost, que va a pasar a recibir una key el repositorio

2021-02-17 15:30 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/ConfigurationSolverImpl.kt
> +    override fun getConfigurationHashFor(@Nonnull customOptionId: String): String {
Done!

2021-02-17 16:20 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/offline_methods/OfflineMethodsViewModel.kt
> +    tracker: MPTracker,
Podríamos cambiar el orden? :P

2021-02-17 16:22 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/offline_methods/OfflineMethodsViewModel.kt
> +    tracker: MPTracker,
podemos

2021-02-17 17:41 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/AmountConfigurationRepositoryImpl.kt
> +                configurationSolver.getAmountConfigurationFor(paymentTypeId)!!
Mandale la excepción como arriba acá en vez de forzarlo

2021-02-17 18:15 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/Mapper.kt
> +abstract class Mapper<T, V> {
Por que le sacamos el internal?

2021-02-17 18:27 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/ExperimentsRepositoryImpl.kt
> +internal class ExperimentsRepositoryImpl(private val sharedPreferences: SharedPreferences) : ExperimentsRepository {
Esta clase no usa el sistema nuevo por algo en particular?

2021-02-17 18:28 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/mappers/PaymentMethodMapper.kt
> +        val paymentMethodById = paymentMethodRepository.getPaymentMethodById(value.first)
Y si lo escribimos de esta forma?

```
return paymentMethodRepository.getPaymentMethodById(value.first).also { paymentMethod ->
          check(paymentMethod) { "Payment method not found" }
          paymentMethod.paymentTypeId = value.second 
}
```
el `check` por detrás lanza un `IllegalStateException`.

2021-02-17 18:46 UTC, jorGonzalez291292 commented on px-checkout/src/test/java/com/mercadopago/android/px/internal/datasource/PaymentServiceTest.java
> +        final Card card = initResponse.getCardById(cardId);
Esto lo podemos mover arriba? :P

2021-02-17 19:38 UTC, cgaggino commented on px-checkout/src/test/java/com/mercadopago/android/px/internal/datasource/PaymentServiceTest.java
> +        final Card card = initResponse.getCardById(cardId);
lo podemos mover!

2021-02-17 19:47 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/AmountConfigurationRepositoryImpl.kt
> +                configurationSolver.getAmountConfigurationFor(paymentTypeId)!!
Dale, ahi generalizo los 3 errores mejor, como estaba antes

2021-02-17 19:48 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/Mapper.kt
> +abstract class Mapper<T, V> {
nice catch, se vé que quedó de alguna prueba, no hace falta quitarle el internal

2021-02-17 19:54 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/ExperimentsRepositoryImpl.kt
> +internal class ExperimentsRepositoryImpl(private val sharedPreferences: SharedPreferences) : ExperimentsRepository {
Porque no migré todos los repositorios, a priori puse los nuevos y a los que agregue que empiecen a storear algo, los que ya estaban habria que relevar a cual le sirve y cual no y cambiarlo, podría ser otro refactor

2021-02-17 19:55 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/mappers/PaymentMethodMapper.kt
> +        val paymentMethodById = paymentMethodRepository.getPaymentMethodById(value.first)
ahi lo escribí de otra forma mas concreta, me parece que la oportunidad es eliminar el if mas que nada

2021-02-17 20:54 UTC, jorGonzalez291292 approved these changes

2021-02-18 18:58 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/di/Session.java
> +            initRepository = new InitService(paymentSettings, getExperimentsRepository(),
Turbina que sea abstract

2021-02-18 20:25 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/NonNullMapper.kt
> +    abstract fun map(value: T): V?
NonNullMapper que devuelve null? :P

2021-02-18 20:30 UTC, guchito9 commented on px-checkout/src/test/java/com/mercadopago/android/px/securitycode/DisplayDataUseCaseTest.kt
> +    lateinit var expressMetadataRepository: ExpressMetadataRepository
No debería ser privado?

2021-02-18 20:37 UTC, guchito9 requested changes

2021-02-18 20:37 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/InitService.java
>  public abstract class InitService implements InitRepository {
Hay que sacarle el abstract

2021-02-18 20:55 UTC, guchito9 approved these changes

2021-02-18 21:53 UTC, guchito9 approved these changes

2021-02-18 21:54 UTC, merged