[Feature] Application model added
mercadopago/px-android pull request #2428
Opened 2021-02-19 21:56 UTC by jorGonzalez291292

Se agrega modelo Application para tarjetas combo.
Se refactoriza InitResponse.

2021-02-19 22:00 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.java
> +    @NonNull private final com.mercadopago.android.px.internal.services.CheckoutService checkoutService;
No se puede importar esto como la gente?

2021-02-19 22:00 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.java
> +        @NonNull final ESCManagerBehaviour escManagerBehaviour, @NonNull final com.mercadopago.android.px.internal.services.CheckoutService checkoutService,
Idem arriba

2021-02-19 22:02 UTC, guchito9 requested changes
Para mi ExpressMetadataInternal debería llamarse simplemente "OneTap"

2021-02-19 23:56 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.java
> +    @NonNull private final com.mercadopago.android.px.internal.services.CheckoutService checkoutService;
Que verde, cambiado!

2021-02-19 23:56 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.java
> +        @NonNull final ESCManagerBehaviour escManagerBehaviour, @NonNull final com.mercadopago.android.px.internal.services.CheckoutService checkoutService,
iden

2021-02-22 16:38 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/CheckoutRepository.kt
> +    fun init(): MPCall<CheckoutResponse>
esto se podria llamar checkout mas que init no? continuando con el renombre

2021-02-22 16:42 UTC, cgaggino commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/Application.kt
> +@Parcelize
por que es parcelable?

2021-02-22 16:46 UTC, cgaggino commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/CheckoutResponse.kt
> +    val oneTap: List<ExpressMetadataInternal>? = null
por que es nullable one tap?

2021-02-22 16:53 UTC, jorGonzalez291292 commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/Application.kt
> +@Parcelize
Por que OneTapItem (ExpressMetadaInternal) es parcelable.

2021-02-22 16:55 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/CheckoutRepository.kt
> +    fun init(): MPCall<CheckoutResponse>
Dale, lo cambio.

2021-02-22 16:55 UTC, jorGonzalez291292 commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/CheckoutResponse.kt
> +    val oneTap: List<ExpressMetadataInternal>? = null
Mala mia. Lo cambio.

2021-02-22 19:46 UTC, cgaggino approved these changes

2021-02-22 20:15 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.java
> +                for (final ExpressMetadata node : oneTap) {
Yo acá lo usaría como OneTapItem ya. También le pondría oneTapItems a la lista

2021-02-22 20:21 UTC, guchito9 approved these changes

2021-02-22 20:48 UTC, merged