modal implementation
mercadopago/px-android pull request #2552
Opened 2021-09-03 19:39 UTC by luissilva-meli

Remedies screen improvements and modal implementation when Market Credits

## Motivación y Contexto

## Descripción
- Improvements to the remedies screen layout.
- When the suggestion is Mercado Credits, the button to pay will open a modal.

## Cómo probarlo
- User with Market Credits enabled.
- Mock
   Check-out: https://run.mocky.io/v3/4bcbd3d1-1d16-4caf-a9c7-fe2fc709416a
   Remedies: https://run.mocky.io/v3/fd435a82-681b-4ae4-995b-a16429f4d534

## Screenshots
https://ibb.co/w01sBFz

## Tipo de cambio (para el release manager)
- [ ] Breaking change (Fix o feature que cambia una funcionalidad existente o rompe firmas)

- [ ] Mi cambio afecta a los integradores internos

## Compartir conocimiento

2021-09-03 19:43 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsLowResFragment.java
> +
Esta tarjeta se usa en el checkout también, no podemos borrar la implementación

2021-09-06 18:24 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsLowResFragment.java
> +
listo.

2021-09-06 19:33 UTC, cardosodiego approved these changes

2021-09-08 17:28 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +    private var showModalRemedies: Boolean = true
this could be moved to the viewmodel, so we keep separated responsabilities. it could have a better name, like "showRemediesModal"

2021-09-08 17:38 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +            viewModel.remedyMessageModal.value?.let { dataModal ->
Maybe this logic could be triggered with an observer, so in here we just set the value of viewModel.remedyMessageModal and that triggers the modal popup? 
@guchito9 que te parece?

2021-09-08 17:41 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +        fun paymentWithModal()
this could be have better naming, like "pay" or "payFromModal"?

2021-09-08 17:51 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +                    viewModel.onButtonPressed(PaymentResultButton.Action.valueOf(genericDialogAction.type.name))
this could lead to unexpected behavior, we are getting a PaymentResultButton.Action value from an ActionType value name and this will only work when both enums have the same exact names. i would change this to map the exact PaymentResultButton.Action value we want in here

2021-09-08 17:52 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +                    showModalRemedies = false;
";" not needed at the end of the line, this is kotlin 💪🏽

2021-09-08 17:58 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +                previousPaymentModel.remedies.suggestedPaymentMethod?.modal?.let { modalMessageRemedies ->
"modalMessageRemedies" could have a better naming, like the one in the next line ("remedyMessageModal")

2021-09-08 18:09 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsMiniResFragment.java
> +    protected void showDisplayInfo(final View view, @NonNull final ConsumerCreditsDisplayInfo displayInfo) { }
is it correct for this to have an empty body? (just asking, i don't know if it should be filled with something like in ConsumerCreditsLowResFragment)

2021-09-08 18:13 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/view/RetryPaymentFragment.kt
>  import com.mercadopago.android.px.internal.features.express.slider.PaymentMethodLowResDrawer
keep an eye on unused imports 😄

2021-09-08 18:24 UTC, francofusaro commented on px-checkout/src/main/res/layout/px_remedies.xml
> +
unnecessary empty line

2021-09-08 18:25 UTC, francofusaro commented on px-checkout/src/main/res/layout/px_remedies.xml
> +
unnecessary empty line

2021-09-10 12:51 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +    private var showModalRemedies: Boolean = true
listo

2021-09-10 12:51 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +        fun paymentWithModal()
listo

2021-09-10 12:52 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +                    viewModel.onButtonPressed(PaymentResultButton.Action.valueOf(genericDialogAction.type.name))
listo

2021-09-10 12:52 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesFragment.kt
> +                    showModalRemedies = false;
listo

2021-09-10 12:52 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +                previousPaymentModel.remedies.suggestedPaymentMethod?.modal?.let { modalMessageRemedies ->
listo

2021-09-10 12:52 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsMiniResFragment.java
> +    protected void showDisplayInfo(final View view, @NonNull final ConsumerCreditsDisplayInfo displayInfo) { }
listo

2021-09-10 12:52 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/view/RetryPaymentFragment.kt
>  import com.mercadopago.android.px.internal.features.express.slider.PaymentMethodLowResDrawer
listo

2021-09-10 12:52 UTC, luissilva-meli commented on px-checkout/src/main/res/layout/px_remedies.xml
> +
listo

2021-09-10 12:53 UTC, luissilva-meli commented on px-checkout/src/main/res/layout/px_remedies.xml
> +
listo

2021-09-10 13:02 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +    private var isShowModal = false
this naming could be "showedModal" (because it represents if we have already showed the modal and the user clicked a button).

2021-09-10 13:15 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +    private var isShowModal = false
listo

2021-09-14 20:16 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodMiniResDrawer.java
> +        return CardLowResFragment.getInstance(drawableFragmentItem);
Te falta poner las mini de los demás medios de pago.

Ya están releaseadas en card-drawer 2.18.0 así que no debería ser muy complicado

2021-09-15 18:47 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/view/RetryPaymentFragment.kt
> +            val paymentMethodFragment = drawableFragmentItem.draw(PaymentMethodMiniResDrawer()) as PaymentMethodFragment<*>
No hay que chequear acá el tipo que viene de backend para ver que drawer usar?

2021-09-15 18:47 UTC, guchito9 commented on gradle.properties
> +cardDrawer=2.18
Esto no es necesario, con la 2.+ debería traer siempre la última

2021-09-16 12:38 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/view/RetryPaymentFragment.kt
> +            val paymentMethodFragment = drawableFragmentItem.draw(PaymentMethodMiniResDrawer()) as PaymentMethodFragment<*>
listo.

2021-09-16 12:47 UTC, luissilva-meli commented on gradle.properties
> +cardDrawer=2.18
listo

2021-09-16 14:20 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/di/MapperProvider.kt
> +        when (cardSize) {
Esto debería ir en una clase aparte como los demás mappers, no acá suelto.

El mapper provider es solo para devolver instancias de mappers.

2021-09-16 14:21 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/CardMediumFragment.kt
> +internal class CardMediumFragment : CardFragment() {
Esta card no la usamos en PX. Si viene esta defaulteamos a la lowres

2021-09-16 17:59 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/di/MapperProvider.kt
> +        when (cardSize) {
listo

2021-09-16 20:08 UTC, guchito9 commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/remedies/RemedyPaymentMethod.kt
> +    val cardSize: String?
Esto debería ser un CardSize directamante

2021-09-16 20:09 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/CardSize.kt
> +    LARGE("large"),
Deberíamos usar los @SerializedName en vez de tener un type

2021-09-16 20:11 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/viewmodel/PaymentResultViewModel.kt
> -    val operationInfo: CongratsResponse.OperationInfo? = null
Por qué borraste este campo?

2021-09-16 20:47 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/viewmodel/PaymentResultViewModel.kt
> -    val operationInfo: CongratsResponse.OperationInfo? = null
ese  "val operationInfo: CongratsResponse.OperationInfo? = null" tava a mais, não estava sendo usado.

2021-09-16 20:58 UTC, luissilva-meli commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/remedies/RemedyPaymentMethod.kt
> +    val cardSize: String?
listo

2021-09-16 20:58 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/CardSize.kt
> +    LARGE("large"),
listo

2021-09-22 18:47 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsFragment.java
> +        final RemediesLinkableMapper remediesLinkableMapper = new RemediesLinkableMapper();
No esta bien que tengamos acá el mapper... debería llegar el modelo (ya mappeado) a usar por la vista.

2021-09-22 18:47 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsLowResFragment.java
> +        final RemediesLinkableMapper remediesLinkableMapper = new RemediesLinkableMapper();
idem al anterior.

2021-09-22 18:47 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsMiniFragment.java
> +public class ConsumerCreditsMiniFragment extends ConsumerCreditsFragment {
Por qué esta clase esta en java? Todas las clases nuevas deberían estar en kotlin.

2021-09-22 19:25 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsXSmallFragment.kt
> +        installment = installmentSelected
En ves de hacer un override de `setInstallment` por que no preguntas en el padre si `topText` es != null para updatear el modelo?

2021-09-22 19:27 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodMiniDrawer.java
> +public class PaymentMethodMiniDrawer implements PaymentMethodFragmentDrawer {
Esta clase debería estar en kotlin

2021-09-22 19:27 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodHighResDrawer.java
> +/* default */ public class PaymentMethodHighResDrawer implements PaymentMethodFragmentDrawer {
por qué es public ahora?

2021-09-22 19:29 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodXSmallDrawer.kt
> +class PaymentMethodXSmallDrawer : PaymentMethodFragmentDrawer{
falta el internal

2021-09-22 19:29 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodXSmallDrawer.kt
> +class PaymentMethodXSmallDrawer : PaymentMethodFragmentDrawer{
faltan espacios ->PaymentMethodFragmentDrawer{

2021-09-22 19:59 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsMiniFragment.java
> +public class ConsumerCreditsMiniFragment extends ConsumerCreditsFragment {
listo.

2021-09-22 19:59 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsXSmallFragment.kt
> +class ConsumerCreditsXSmallFragment : ConsumerCreditsFragment() {
listo.

2021-09-22 19:59 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsXSmallFragment.kt
> +        installment = installmentSelected
listo

2021-09-22 19:59 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodMiniDrawer.java
> +public class PaymentMethodMiniDrawer implements PaymentMethodFragmentDrawer {
listo.

2021-09-22 19:59 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodHighResDrawer.java
> +/* default */ public class PaymentMethodHighResDrawer implements PaymentMethodFragmentDrawer {
Necesito usarlo en mi mapeador "RemediesPaymentMethodMapper".

2021-09-22 19:59 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodXSmallDrawer.kt
> +class PaymentMethodXSmallDrawer : PaymentMethodFragmentDrawer{
listo

2021-09-22 20:15 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/ChangePaymentMethodEvent.kt
> +        private const val PATH = "${BASE_PATH}/result/error/change_payment_method"
Este cambio en el track esta validado?? Ya existe en el catalogo de melidata?

2021-09-22 20:15 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/ChangePaymentMethodEvent.kt
> +    private val event = if(showedModal) "modal" else "view"
Me parece más limpio pasar un Type que sean Modal o View según sea necesario.

2021-09-22 20:15 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/ChangePaymentMethodEvent.kt
> +class ChangePaymentMethodEvent(showedModal: Boolean) : TrackWrapper() {
esto puede ser internal?

2021-09-22 20:24 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodMiniDrawer.kt
> +class PaymentMethodMiniDrawer : PaymentMethodFragmentDrawer {
Puede ser internal?

2021-09-22 20:24 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsMiniFragment.kt
> +class ConsumerCreditsMiniFragment : ConsumerCreditsFragment() {
Puede ser internal?

2021-09-22 20:24 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsMiniFragment.kt
> +    override fun setInstallment(view: View, installmentSelected: Int) {
Acá lo mismo que en el caso anterior.

2021-09-22 20:43 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesLinkableMapper.kt
> +    override fun map(value: LinkableText): LinkableTextRemedies {
Por qué tenemos dos métodos mapper de `LinkableText` a `LinkableTextRemedies`?

2021-09-22 20:43 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/LinkableTextRemedies.kt
> +data class LinkableTextRemedies(
Por qué este modelo solamente esta asociado a remedies? No puede ser usado para la tarjeta de consumer credits en onetap?

2021-09-22 20:45 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesLinkableMapper.kt
> +    override fun map(value: LinkableText): LinkableTextRemedies {
uno se usa en oneTap y el otro en Remedies

2021-09-22 20:55 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/ChangePaymentMethodEvent.kt
> +        private const val PATH = "${BASE_PATH}/result/error/change_payment_method"
Si. Incluyo el campo "from" de modal or view. Sami modificará el catálogo de melidata

2021-09-22 22:24 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/ChangePaymentMethodEvent.kt
> +    private val event = if(showedModal) "modal" else "view"
listo

2021-09-22 22:24 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/ChangePaymentMethodEvent.kt
> +class ChangePaymentMethodEvent(showedModal: Boolean) : TrackWrapper() {
listo

2021-09-23 12:30 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/TrackWrapper.kt
> +        const val MODAL = "modal"
Estas constantes no deberían estar acá... ya que solo son para el contexto del `ChangePaymentMethodEvent`

2021-09-23 12:30 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/TrackWrapper.kt
> +        const val MODAL = "modal"
MODAL y VIEW

2021-09-23 12:33 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/TrackWrapper.kt
> +        const val MODAL = "modal"
Estas constantes tambien son usadas em RemediesEvent cuando temos o track:  px_checkout/result/error/remedy.

2021-09-23 12:41 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +                track(ChangePaymentMethodEvent(isFromModal))
Cual es la diferencia entre `isFromModal` y `showedModal`?

2021-09-23 12:41 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesLinkableMapper.kt
> +    override fun map(value: LinkableText): LinkableTextRemedies {
SI se usa en onetap no debería llamarse remedies.

2021-09-23 12:42 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/TrackWrapper.kt
> +        const val MODAL = "modal"
Sigue estando en el lugar incorrecto, no? `TrackWrapper` no es genérico para todo los tracks?

2021-09-23 12:56 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +                track(ChangePaymentMethodEvent(isFromModal))
IsFromModal proviene de Fragment, por lo que podemos mostrar la lógica si es de Modal o View cuando temos o track de change_payment_method. El showModal que se usa solo dentro del viewModel se usa en el momento de mostrar el modal y para la acción de pago futura.

2021-09-23 12:58 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +    private var showedModal = false
Probamos todo esto con destroy activity?

2021-09-23 12:59 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultPresenter.java
> +            track(new ChangePaymentMethodEvent(false));
Como sabemos que no viene de un modal?

2021-09-23 13:06 UTC, luissilva-meli commented on px-checkout/src/main/res/layout/px_card_view_mini.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
ya era así en otros diseños y seguí el mismo.

2021-09-23 13:07 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/LinkableTextRemedies.kt
> +data class LinkableTextRemedies(
listo

2021-09-23 13:07 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesPaymentMethodMapper.kt
> +        }
Esto quedaría mejor así.

```
return when (cardSize) {
            CardSize.LARGE -> {
                PaymentMethodHighResDrawer()
            }
            CardSize.SMALL,
            CardSize.XSMALL -> {
                PaymentMethodLowResDrawer()
            }
            CardSize.MINI -> {
                PaymentMethodMiniDrawer()
            }
            else -> PaymentMethodLowResDrawer())
        }.let(::drawableFragmentItem.draw) as PaymentMethodFragment<*>
```

2021-09-23 13:07 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesLinkableMapper.kt
> +    override fun map(value: LinkableText): LinkableTextRemedies {
listo

2021-09-23 13:07 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsMiniFragment.kt
> +    override fun setInstallment(view: View, installmentSelected: Int) {
listo

2021-09-23 13:07 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/ConsumerCreditsMiniFragment.kt
> +class ConsumerCreditsMiniFragment : ConsumerCreditsFragment() {
listo

2021-09-23 13:07 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/express/slider/PaymentMethodMiniDrawer.kt
> +class PaymentMethodMiniDrawer : PaymentMethodFragmentDrawer {
listo.

2021-09-23 13:07 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultPresenter.java
> +            track(new ChangePaymentMethodEvent(false));
Actualmente, el modal solo está disponible en la pantalla de remedies cuando se trata de sugerencias de pago en el mercado crédito. Esta track ya existía en Android e incluso comenté en el daily que por defecto sería from: view para este escenario.

2021-09-23 13:07 UTC, luissilva-meli commented on px-checkout/src/main/res/layout/px_card_view_xsmall.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
listo.

2021-09-23 13:56 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/view/LinkableTextView.java
> +    private LinkableTextRemedies model;
Capaz ya lo tenés en la mira, pero si se usa en el modulo de checkout no debería estar atado al contexto de remedies.

2021-09-23 14:36 UTC, jorGonzalez291292 commented on px-checkout/src/main/res/layout/px_activity_payment_result.xml
> +            android:layout_weight="1"/>
Por que agregamos el `layout_weight`? Estoy viendo que esta seteado en el `space`

2021-09-23 14:43 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesLinkableMapper.kt
> +    fun mapRemedies(value: LinkableText): com.mercadopago.android.px.model.LinkableText {
Por lo menos usemos un `typealias` para que no quede con todo con package .
`com.mercadopago.android.px.model.LinkableText`

2021-09-23 14:43 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesLinkableMapper.kt
> +            value.links ?: null
por qué devolvemos `null` si `value.links` ya puede ser null??

2021-09-23 14:47 UTC, francofusaro commented on px-checkout/src/main/res/layout/px_remedies_retry_payment.xml
> +        android:layout_marginStart="16dp"
Estos margins deberian cargarse desde un dimension

2021-09-23 14:49 UTC, jorGonzalez291292 commented on px-checkout/src/main/res/layout/px_remedies_retry_payment.xml
> +        android:layout_marginTop="128dp"
Esto como se ve en diferentes devices??  Debería estar en una constante. Por qué no usamos la propiedad `gravity`?

2021-09-23 14:59 UTC, luissilva-meli commented on px-checkout/src/main/res/layout/px_activity_payment_result.xml
> +            android:layout_weight="1"/>
Para ajustar la pantalla de solución y los términos y condiciones, los textos se alinean a continuación

2021-09-23 15:10 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/model/LinkableText.kt
> +data class LinkableText(
Esto debería ser internal

2021-09-23 15:17 UTC, cgaggino commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +    fun setRemedyModalAbortTrack() {
What are we setting here? seems more like we are tracking.

I would change the method name in order to reflect the main action

2021-09-23 15:29 UTC, cgaggino requested changes
Hi guys, despite correction of the comments, we are experiencing a crash in this branck related to consumer credit.

Here is how to reproduce it: 

<a href="https://ibb.co/LRTLb97"><img src="https://i.ibb.co/MSzYWP0/crash.gif" alt="crash" border="0"></a>

and here is the crash message:

`2021-09-23 11:22:03.770 5335-5335/com.mercadopago.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mercadopago.example, PID: 5335
    java.lang.IllegalStateException: Fragment already added: ConsumerCreditsFragment{9a1c8fe} (0e7c10fe-3b32-4481-aa1f-dd67209b0d45) id=0x7f0a02d2}
        at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:67)
        at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1563)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021`

We need to fix it before merge, or check that is not related to these changes

2021-09-23 15:40 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +    fun setRemedyModalAbortTrack() {
listo!

2021-09-23 17:04 UTC, luissilva-meli commented
> Hi guys, despite correction of the comments, we are experiencing a crash in this branck related to consumer credit.
> 
> Here is how to reproduce it:
> 
> [![crash](https://camo.githubusercontent.com/020a81cc6af342ef7af06a292448120d51dddfc3e5490a7110867027cab8104a/68747470733a2f2f692e6962622e636f2f4d537a595750302f63726173682e676966)](https://ibb.co/LRTLb97)
> 
> and here is the crash message:
> 
> `2021-09-23 11:22:03.770 5335-5335/com.mercadopago.example E/AndroidRuntime: FATAL EXCEPTION: main Process: com.mercadopago.example, PID: 5335 java.lang.IllegalStateException: Fragment already added: ConsumerCreditsFragment{9a1c8fe} (0e7c10fe-3b32-4481-aa1f-dd67209b0d45) id=0x7f0a02d2} at androidx.fragment.app.FragmentStore.addFragment(FragmentStore.java:67) at androidx.fragment.app.FragmentManager.addFragment(FragmentManager.java:1563) at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:405) at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2167) at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1990) at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1945) at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1847) at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:223) at android.app.ActivityThread.main(ActivityThread.java:7656) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 2021`
> 
> We need to fix it before merge, or check that is not related to these changes

listo.

2021-09-23 18:17 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/remedies/RemediesViewModel.kt
> +    private var showedModal = false
listo.

2021-09-24 18:16 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/model/LinkableText.kt
> +internal data class LinkableText(
No existia ya una clase LinkableText? 👀

2021-09-24 18:16 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/model/LinkableText.kt
> +    val links: Map<String?, String?>?
Es correcto que todo sea nullable acá?

2021-09-24 18:17 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/model/LinkableText.kt
> +        val installments: Map<String?, String?>?
Es correcto que todo sea nullable acá?

2021-09-24 18:19 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/model/LinkableText.kt
> +internal data class LinkableText(
sí, esta nueva fue una solución que hice junto con George para poder ensamblar el objeto y cambiar los colores del texto de términos y condiciones.

2021-09-24 18:26 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/model/LinkableText.kt
> +    val links: Map<String?, String?>?
listo

2021-09-24 18:26 UTC, luissilva-meli commented on px-checkout/src/main/java/com/mercadopago/android/px/model/LinkableText.kt
> +        val installments: Map<String?, String?>?
listo.

2021-09-27 20:14 UTC, cardosodiego approved these changes

2021-09-28 16:35 UTC, jorGonzalez291292 approved these changes

2021-09-28 16:37 UTC, cgaggino approved these changes

2021-09-30 15:35 UTC, merged