[Enhancement] PX Core commons and data extensions migration
mercadopago/px-android pull request #2591
Opened 2021-11-09 19:54 UTC by francofusaro

We migrated some helpers, utils and extensions from commons and data layer that are used on multiple projects to the new module px-core.

## Motivación y Contexto
We are starting to attack the problem of code duplication across our multiple projects.

## Descripción
Commons moved functionality:
- CoroutineContextProvider
- ParcelableUtil, ParcelableUtil (kt) and ParcelExt --> ParcelExt
- StringExt, StringUtil, TextUtil and text part of BaseExt --> StringExt
- Some extensions that are on BaseExt that apply for anything --> AnyExt
- JsonUtil --> GsonExt (We are now extending Gson instead of having JsonUtil so projects can use their own Gson instance)

Data moved functionality:
- Response/ApiResponse and ResponseExt --> Response and ResponseExt (We generified response extensions where we can to avoid restricting them to Throwable)
- ConnectionHelper
- FileHelper and FileManager read/write extensions --> FileExt (We are also using Gson as parameter on some functions that needs it, to keep our idea that every project can use their own Gson instance)

**IMPORTANT: We haven't moved the code that actually uses these extensions yet, that has to be evaluated to avoid breaking stuff.**

2021-11-20 00:14 UTC, jvillada31 approved these changes
LG, left some minor suggestions/questions

2021-11-20 00:14 UTC, jvillada31 commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/extensions/StringExt.kt
> +const val CSV_DELIMITER = ","
Given that this is not private and can be used outside this file should we use a more generic name, something like`COMMA` similar to `EMPTY` or `SPACE`?

2021-11-20 00:14 UTC, jvillada31 commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/extensions/StringExt.kt
> +private val PLACE_HOLDER_PATTERN: Pattern = Pattern.compile("\\{[0-9]*\\}");
I think is safe to remove the comma at the end

2021-11-20 00:14 UTC, jvillada31 commented on px-core/src/main/java/com/mercadopago/android/px/core/data/network/ConnectionHelper.kt
> +    private val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
Nitpicking: I know this is private but I think we should avoid abbreviation in favor of readability

2021-11-23 12:47 UTC, francofusaro commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/extensions/StringExt.kt
> +// For java usage
does this makes sense to you? because i am not sure if we should keep it 🤔

2021-11-23 14:39 UTC, jvillada31 commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/extensions/StringExt.kt
> +// For java usage
Yes it does, sorry about the astronaut, is confusing, my bad 🙃

2021-11-30 17:21 UTC, guchito9 commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/extensions/StringExt.kt
> +private val PLACE_HOLDER_PATTERN: Pattern = Pattern.compile("\\{[0-9]*\\}")
El tipado parece al pedo, lo debería inferir

2021-11-30 17:50 UTC, guchito9 commented on px-core/src/test/java/com/mercadopago/android/px/core/ExampleUnitTest.kt
> +class ExampleUnitTest {
Este habría que borrarlo

2021-11-30 17:52 UTC, guchito9 requested changes
Ver las dos giladas que comenté y mergeamos

2021-11-30 19:35 UTC, guchito9 approved these changes

2021-11-30 19:46 UTC, merged