[PXN-3237] update total value field
mercadopago/px-android pull request #2671
Opened 2022-03-07 22:24 UTC by cardosodiego

## Motivación y Contexto

## Descripción

## Cómo probarlo

## Screenshots

## Tipo de cambio (para el release manager)
- [ ] Breaking change (Fix o feature que cambia una funcionalidad existente o rompe firmas)

- [ ] Mi cambio afecta a los integradores internos

## Compartir conocimiento

2022-03-14 18:54 UTC, francofusaro requested changes
Left some comments!
It would be great if we can add CHANGELOG changes as we discussed on Android Sync 🙈

2022-03-14 18:54 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +            val isChecked = state.splitSelectionState.userWantsToSplit()
i think it may be better to access this only when it's needed (inside the if (selected >= 0)), what do you think?

2022-03-14 18:54 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +                paymentTypeId == PaymentInfo.PaymentMethodType.CREDIT_CARD.value)
We have a function for this on PaymentTypes, called "isCreditCardPaymentType"

2022-03-14 18:54 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +        val chargeRule = chargeRepository.getChargeRule(paymentTypeId)
This code is pretty similar to the other map function, can we extract the common code?

2022-03-17 12:51 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +        val chargeRule = chargeRepository.getChargeRule(paymentTypeId)
listo!

2022-03-17 12:53 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +            val isChecked = state.splitSelectionState.userWantsToSplit()
Yes, I agree. I made some adjustments and refactoring the methods to use only 1 instead 3 like before

2022-03-17 12:53 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +            val amountConfiguration = amountConfigurationRepository.getConfigurationSelectedFor(customOptionId)
Yeap :P.  Done!

2022-03-17 12:55 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +    private fun refreshTotalValue() {
Yeah! I made some adjustments and refactoring to use only 1 function instead 3 like before :)

2022-03-17 12:57 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +    private fun changeTotalValue() {
I agree with you. After the changes made we have only 1 function which is updateTotalValue

2022-03-17 12:58 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +        return  (customOptionId == PaymentInfo.PaymentMethodType.CONSUMER_CREDITS.value ||
Done! 👍🏻

2022-03-17 12:58 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +                paymentTypeId == PaymentInfo.PaymentMethodType.CREDIT_CARD.value)
Done! Thanks for the tip. 😄

2022-03-17 13:00 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +    fun mapTotalInterestFree(
I refactored this functions but still in SummaryViewModelMapper. In your opinion, which package or file should we create for this situation?

2022-03-17 13:19 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +            val amountConfiguration = amountConfigurationRepository.getConfigurationSelectedFor(customOptionId)
has this changed? because i still see it's the same as this line:
val selected = amountConfigurationRepository.getConfigurationSelectedFor(customOptionId)

2022-03-17 13:35 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +            val amountConfiguration = amountConfigurationRepository.getConfigurationSelectedFor(customOptionId)
Ops. Now it's changed 😅 
I didn't understand and notice the line duplicated before.  Sorry...
Done!

2022-03-18 13:28 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +    fun mapTotalInterestFree(
Maybe we should discuss this in a meeting 😄

2022-04-25 15:52 UTC, samantaalbanez submitted a review, later dismissed

2022-04-27 16:52 UTC, jvillada31 commented on CHANGELOG.md
> +* FIX - Adjust track offline_methods.
```suggestion
* FIX - Adjust track offline_methods.
```

2022-04-27 17:02 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +            }
@cardosodiego we should inject this `SummaryViewModelMapper ` as a parameter for the `OneTapPresenter` constructor

Plese check `private OneTapPresenter createPresenter()` in `OneTapFragment`

2022-04-27 17:04 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +                    )
@cardosodiego please check if we can make this logic inside the mapper reading the params given -> pass the amountConfiguration to the mapper and do this internally

2022-04-27 17:07 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +                    )
Nice to have!!!

2022-04-27 17:11 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryModelMapper.kt
> +        summaryDetailDescriptorMapper)
```suggestion
        summaryDetailDescriptorMapper
)
```

2022-04-27 17:31 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +    private val summaryDetailDescriptorMapper: SummaryDetailDescriptorMapper): Mapper<CustomTotal, SummaryView.Model>() {
```suggestion
    private val summaryDetailDescriptorMapper: SummaryDetailDescriptorMapper
): Mapper<CustomTotal, SummaryView.Model>() {
```

2022-04-27 21:40 UTC, cardosodiego commented on CHANGELOG.md
> +* FIX - Adjust track offline_methods.
done!

2022-04-27 21:41 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +            }
done!

2022-04-27 21:42 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryModelMapper.kt
> +        summaryDetailDescriptorMapper)
done!

2022-04-28 12:28 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +                    )
done

2022-04-28 12:33 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +    private val summaryDetailDescriptorMapper: SummaryDetailDescriptorMapper): Mapper<CustomTotal, SummaryView.Model>() {
done

2022-04-28 18:38 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +    }
We could instantiate this outside of the `OneTapPresenter` and provide it as a dependency using the constructor

2022-04-28 20:47 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +    }
done!

2022-04-29 15:16 UTC, jvillada31 approved these changes
LGTM

Left a question 👀 , code looks so much better now, thanks for the updates

@samantaalbanez @cardosodiego can we add a comment here with the ticket that we are going to be working on to improve the cache logic?

Thanks

2022-04-29 15:59 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapFragment.java
> +
done !

2022-04-29 16:00 UTC, jvillada31 approved these changes

2022-04-29 16:05 UTC, samantaalbanez commented
Create task for adjust cache -> https://mercadolibre.atlassian.net/browse/PXN-3756

2022-04-29 16:47 UTC, jvillada31 approved these changes

2022-05-03 22:12 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryModelMapper.kt
> +        customOptionId: String, paymentTypeId: String): SummaryView.Model {
```suggestion
    private fun createModel(customOptionId: String, paymentTypeId: String): SummaryView.Model {
```

2022-05-03 22:17 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryModelMapper.kt
> +        customOptionId: String, paymentTypeId: String): SummaryView.Model {
done !

2022-05-03 22:21 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +        //return createSummaryViewModel(value)
@samantaalbanez 😭 
```suggestion
```

2022-05-03 22:24 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +        //return createSummaryViewModel(value)
done 😂

2022-05-04 12:26 UTC, jvillada31 approved these changes
LG, thanks for the updates @samantaalbanez 🚀 

@francofusaro can you take a look? Cache is now being used (working as expected) and the payer cost is being calculated also as it should.

2022-05-04 15:22 UTC, francofusaro reviewed
Left some comments, it's almost done 🥳

2022-05-04 16:44 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +    private val chargeAmount: BigDecimal
done

2022-05-04 16:45 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +        val chargeAmount = getPayerCost(value, discountModel)
done

2022-05-04 16:47 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +    val isChecked: Boolean = false,
done

2022-05-04 16:50 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +    private fun getPayerCost(value: CustomTotal, discountModel: DiscountConfigurationModel): BigDecimal {
done

2022-05-04 16:51 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/SummaryViewModelMapper.kt
> +        return (other.discountConfigurationModel == discountConfigurationModel
done

2022-05-04 17:03 UTC, francofusaro submitted a review, later dismissed
Let's goo 💪💪💪

2022-05-04 23:24 UTC, jvillada31 approved these changes
🚀

2022-05-05 13:08 UTC, francofusaro approved these changes

2022-05-05 13:10 UTC, merged