[ENHANCEMENT] Tokenization logic is decoupled
mercadopago/px-android pull request #2677
Opened 2022-03-16 14:36 UTC by jorGonzalez291292

## Descripción
Since we need to return a tokenized card so integrators can process a payment, we had to decouple the tokenization logic from the payment flow when PX is started as a payment method selector.

https://user-images.githubusercontent.com/50373979/158612662-f4a06d8c-3f3b-429c-b06b-5348bc203d3c.mp4

https://user-images.githubusercontent.com/50373979/158612869-dea66b00-8485-47e4-984d-871f12ee65d6.mp4

https://user-images.githubusercontent.com/50373979/158613692-26a5e8ee-d90c-481d-8ad1-d5a39c97de79.mp4

https://user-images.githubusercontent.com/50373979/158613877-1e54fe01-472c-465b-b4fd-12255e8e3faf.mov

2022-03-29 15:16 UTC, francofusaro reviewed
left some minor comments! nice refactor 😄

2022-03-29 15:16 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/model/exceptions/MercadoPagoError.java
> +    private static final long serialVersionUID = 8365047557796395851L;
what is this used for? 👀

2022-03-29 15:16 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/model/exceptions/SecurityCodeRequiredError.kt
> +) : MercadoPagoError("Error reason: ${reason.name.toLowerCase(Locale.getDefault())}", true)
missing new line 😅

2022-03-29 15:16 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/model/internal/PaymentConfigurationMapper.kt
> +)
missing new line 😅

2022-03-29 18:37 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/base/use_case/TokenizeWithEscUseCase.kt
> +        val card = userSelectionRepository.card
Maybe start the method like this:
override suspend fun doExecute(param: Unit) = with(userSelectionRepository.card) {

2022-03-29 18:47 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/base/use_case/UserSelectionUseCase.kt
> +        param.payerCost?.also(userSelectionRepository::select)
let

2022-03-29 18:51 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/base/use_case/TokenizeWithEscUseCase.kt
> +        val card = userSelectionRepository.card
@guchito9 With the `with` I think it is less readable.
Ej:
```
with(userSelectionRepository.card) {
if (PaymentTypes.isCardPaymentType(userSelectionRepository.paymentMethod?.paymentTypeId)) {
            if (this != null && hasPayerCost()) {
                tokenizeCard(this)
            } else if (hasValidNewCardInfo()) {
                Response.Success(Token())
            } else {
                Response.Failure(MercadoPagoError("Something went wrong", false))
            }
        } else {
            Response.Success(Token())
        }
}
```

@francofusaro

2022-03-29 19:11 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/base/use_case/TokenizeWithEscUseCase.kt
> +        return if (shouldTokenizeWithCvv(card)) {
Maybe later.

2022-03-29 19:14 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/model/exceptions/MercadoPagoError.java
> +    private static final long serialVersionUID = 8365047557796395851L;
I was asked by the class to extend serializable.

2022-03-29 19:23 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultActivity.java
> +        if (remediesFragment == null || payButtonFragment == null) {
It was already like this :P

2022-03-29 19:44 UTC, francofusaro approved these changes

2022-03-31 14:25 UTC, guchito9 requested changes

2022-04-04 16:46 UTC, jorGonzalez291292 commented
Ahí reviso los test. 
Respecto al pedido de la huella... PayButton lo pide siempre y esta la implementación mock del behaviour en la test app privada.

2022-04-04 16:56 UTC, francofusaro commented
> Ahí reviso los test. Respecto al pedido de la huella... PayButton lo pide siempre y esta la implementación mock del behaviour en la test app privada.

Claro, eso entiendo, pero comparando el video ese con el primer video (y con el cuarto) veo que no es el mismo comportamiento, en esos videos despues del CVV no te pide la huella, en cambio en el del remedy si

2022-04-04 17:01 UTC, jorGonzalez291292 commented
En los videos del 1 al 4 en ningún momento pide huella por que en ese momento no estaba mergeado el mock que hiciste para la huella jajaja

2022-04-05 13:22 UTC, merged