Feature/draw card bank account
mercadopago/px-android pull request #2681
Opened 2022-03-22 13:43 UTC by daniivillegas

## Descripción

- Account registration card design is added.
- The card registration design is changed

## Cómo probarlo
Run tetapp with this mock https://run.mocky.io/v3/e05513fb-dc27-438f-bbac-a39028b52e57 ;)

## Screenshots
<img src="https://user-images.githubusercontent.com/81260775/159494738-7d9a9433-9a9b-46ad-aa84-dc50de059464.png" width="40%" />

<img src="https://user-images.githubusercontent.com/81260775/159494749-7d3bad5a-5347-41f6-a570-cd5748ae5c9a.png" width="40%" />

## Compartir conocimiento
Debin etapa 1: https://www.figma.com/file/BS6BJS9IDL2LkHcfpeubfy/DEBIN?node-id=3104%3A114461

2022-03-22 15:25 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +            view.getBackground().setColorFilter(ColorUtils.safeParcelColor(backgroundColor, DEFAULT_BACKGROUND_COLOR), PorterDuff.Mode.SRC_ATOP);
Se me hace que esta función de set color filter a un drawable la podemos tener en el core porque la estamos utilizando arriba también y nos podría ser útil, algo como un Drawable.setBackgroundColor, que te parece? 
Pregunta, que pasa si backgroundColor viene null? Se queda con el color que tenga el drawable no?

2022-03-22 15:27 UTC, francofusaro commented on px-checkout/src/main/res/layout/px_other_payment_method_card_view_large.xml
> +<com.google.android.material.card.MaterialCardView xmlns:android="http://schemas.android.com/apk/res/android"
🚀

2022-03-22 15:31 UTC, francofusaro commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/utils/ColorUtils.kt
> +    fun safeParcelColor(color: String?, defaultColor: Int) = runCatching {
🥇 Gracias por tu contribución al core

2022-03-22 18:12 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +                drawable.setColorFilter(ColorUtils.safeParcelColor(border.getColor(), DEFAULT_BORDER_COLOR), PorterDuff.Mode.SRC_ATOP);
decis tener todos los default en un resource?

2022-03-22 18:12 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +    private static final float WITHOUT_CARD_ELEVATION = 0f;
no :P

2022-03-22 18:14 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +            view.getBackground().setColorFilter(ColorUtils.safeParcelColor(backgroundColor, DEFAULT_BACKGROUND_COLOR), PorterDuff.Mode.SRC_ATOP);
Dale de una,  lo movemos. Si no viene el background utiiza el drawable, como vos decis

2022-03-22 18:44 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/CardViewHelper.kt
> +            else -> R.drawable.card_view_dotted_border
Dale, vamos por un no border por default, lo del elevation lo dejo a tu criterio 😛

2022-03-22 18:44 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +            cardView.setCardElevation(WITHOUT_CARD_ELEVATION);
Cual sería el nombre no tan descriptivo?

2022-03-22 18:45 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +                drawable.setColorFilter(ColorUtils.safeParcelColor(border.getColor(), DEFAULT_BORDER_COLOR), PorterDuff.Mode.SRC_ATOP);
si, tener los default como resources

2022-03-22 19:06 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +            cardView.setCardElevation(WITHOUT_CARD_ELEVATION);
mala mia, no dije nada jajaja

2022-03-22 20:34 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +            if (drawable != null) {
Y si metemos el chequeo de null dentro de la extension? 🤔 Y hacemos que la extensión sea para "Drawable?"

2022-03-23 16:06 UTC, jorGonzalez291292 commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/extensions/DrawableExt.kt
> +fun Drawable?.setBackgroundColor(backgroundColor: String?, defaultColor: Int) {
internal

2022-03-23 16:06 UTC, jorGonzalez291292 commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/extensions/DrawableExt.kt
> +fun Drawable?.setBackgroundColor(backgroundColor: String?, defaultColor: Int) {
Rename `setBackgroundColor` to `setColorFilter`. Can defaultColor have default value?

2022-03-23 16:12 UTC, jorGonzalez291292 commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    public String getDeepLink() {
In what cases of OfflinePaymentMethods do we use this deeplink?

2022-03-23 16:13 UTC, daniivillegas commented on px-core/src/main/java/com/mercadopago/android/px/core/commons/extensions/DrawableExt.kt
> +fun Drawable?.setBackgroundColor(backgroundColor: String?, defaultColor: Int) {
Ok, the default color can be transparent? :P

2022-03-23 16:14 UTC, francofusaro requested changes

2022-03-23 16:14 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/CardViewHelper.kt
> +        else -> R.drawable.card_view_none_border
que te parece card_view_borderless? 😂

2022-03-23 16:14 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +    private static final float WITH_ELEVATION = 2f;
Se me hace que estaría bueno ponerle un nombre tipo "SMALL/MEDIUM/LARGE_ELEVATION", más que nada por si a futuro necesitamos otro, que opinas? 🤔

2022-03-23 16:14 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +        final MaterialCardView cardView = (MaterialCardView) view;
Podemos guardar directamente las referencias como "MaterialCardView" o nos trae algun problema eso? Más que nada para evitar estos casteos que se repiten

2022-03-23 16:14 UTC, francofusaro commented on px-checkout/src/main/res/drawable/card_view_dotted_border.xml
> +        android:width="2dp"
Usemos dimens para esto 😄

2022-03-23 16:14 UTC, francofusaro commented on px-checkout/src/main/res/drawable/card_view_solid_border.xml
> +    <stroke android:width="2dp" />
Simil arriba, usemos dimens

2022-03-23 16:14 UTC, francofusaro commented on px-checkout/src/main/res/layout/px_other_payment_method_card_view_large_medium_res.xml
> +</com.google.android.material.card.MaterialCardView>
Te falta el salto de linea 😂

2022-03-23 16:14 UTC, francofusaro commented on px-checkout/src/main/res/layout/px_other_payment_method_card_view_large.xml
> +</com.google.android.material.card.MaterialCardView>
falta el salto de linea 🧂⭕

2022-03-23 16:14 UTC, francofusaro commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    private final String iconUrl;
Estos nuevos campos son nullables o no nullables?

2022-03-23 16:14 UTC, daniivillegas commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    public String getDeepLink() {
No, that's why it's nullable. From back comes the same signature for new card and offline method.

2022-03-23 16:14 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/CardViewHelper.kt
> +        else -> R.drawable.card_view_none_border
oks

2022-03-23 16:15 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +    private static final float WITH_ELEVATION = 2f;
Y a este cual nombre le pondrias? jaja

2022-03-23 16:16 UTC, daniivillegas commented on px-checkout/src/main/res/layout/px_other_payment_method_card_view_large_medium_res.xml
> +</com.google.android.material.card.MaterialCardView>
lacon jajajaja

2022-03-23 16:17 UTC, daniivillegas commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    private final String iconUrl;
DeepLink, iconUrl not null. Desde back la firma va a ser igual para new card y offline method

2022-03-23 16:21 UTC, jorGonzalez291292 commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    private final String iconUrl;
All this info, shouldn't it go inside the `DisplayInfo`?

2022-03-23 16:24 UTC, daniivillegas commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    private final String iconUrl;
I don't know if it makes sense for the deeplink to be inside the display info, the other fields can be. I take it to talk to the people in the backend

2022-03-23 17:59 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +    private static final float WITH_ELEVATION = 2f;
y no sé, 2f parece algo relativamente small jajajjaa

2022-03-23 18:00 UTC, francofusaro commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    private final String iconUrl;
entonces pongamosle el annotation correspondiente asi evitamos los problemas jajaja, o migrame la clase a kotlin(?

2022-03-25 13:30 UTC, daniivillegas commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    private final String iconUrl;
I talked about it with the backend people and in the end it will come up in the info display

2022-03-25 13:31 UTC, daniivillegas commented on px-services/src/main/java/com/mercadopago/android/px/model/OfflinePaymentTypesMetadata.java
> +    private final String iconUrl;
Hable con la gente de back y va a venir todo en el display info (menos el deeplink)

2022-03-28 13:12 UTC, francofusaro approved these changes

2022-03-28 13:15 UTC, jorGonzalez291292 approved these changes

2022-03-28 13:16 UTC, merged