[PXN-3415] getPaymentTypeId null
mercadopago/px-android pull request #2690
Opened 2022-03-28 22:07 UTC by samantaalbanez

## Motivación y Contexto

## Descripción

## Cómo probarlo

## Screenshots

## Tipo de cambio (para el release manager)
- [ ] Breaking change (Fix o feature que cambia una funcionalidad existente o rompe firmas)

- [ ] Mi cambio afecta a los integradores internos

## Compartir conocimiento

2022-03-29 05:03 UTC, jvillada31 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentMethodRepositoryImpl.kt
> +        return value.firstOrNull { it.id == paymentMethodId } ?: throw IllegalStateException("PaymentTypeId null")
@samantaalbanez I updated this, can you test the crash with this update?

Also can we update the IllegalStateException to

```suggestion
        return value.firstOrNull { it.id == paymentMethodId } ?: throw IllegalStateException("PaymentMethod not foundl")
```

2022-03-29 15:04 UTC, RoBarriosG approved these changes

2022-03-29 16:23 UTC, davburgos approved these changes

2022-03-29 17:25 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentMethodRepositoryImpl.kt
> +        return value.firstOrNull { it.id == paymentMethodId } ?: throw IllegalStateException("PaymentMethod not found")
I think we could use strings.xml and put the message in Portuguese, Spanish and English. What do you think?

2022-03-29 17:46 UTC, cardosodiego submitted a review, later dismissed

2022-03-29 17:51 UTC, cardosodiego submitted a review, later dismissed

2022-03-29 18:11 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentMethodRepositoryImpl.kt
> +        return value.firstOrNull { it.id == paymentMethodId } ?: throw IllegalStateException("PaymentMethod not found")
I don't think it's needed, because it's not intended for the user, just a debug log

2022-03-29 18:13 UTC, guchito9 requested changes

2022-03-29 18:13 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentMethodRepositoryImpl.kt
> +    override fun getPaymentMethodById(paymentMethodId: String): PaymentMethod? {
You forgot to change the signature of the parent method to return PaymentMethod not nullable

2022-03-29 18:18 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentMethodRepositoryImpl.kt
> +    override fun getPaymentMethodById(paymentMethodId: String): PaymentMethod? {
adjusted

2022-03-29 19:09 UTC, RoBarriosG submitted a review, later dismissed

2022-03-30 13:22 UTC, cardosodiego approved these changes

2022-03-30 14:16 UTC, daniivillegas submitted a review, later dismissed

2022-03-30 15:05 UTC, guchito9 approved these changes

2022-03-30 15:05 UTC, cardosodiego submitted a review, later dismissed

2022-03-30 17:04 UTC, cardosodiego approved these changes

2022-03-30 17:05 UTC, merged