feature/added-tag-cc
mercadopago/px-android pull request #2693
Opened 2022-04-01 01:32 UTC by cardosodiego

## Motivación y Contexto

## Descripción

## Cómo probarlo

## Screenshots

## Tipo de cambio (para el release manager)
- [ ] Breaking change (Fix o feature que cambia una funcionalidad existente o rompe firmas)

- [ ] Mi cambio afecta a los integradores internos

## Compartir conocimiento

2022-04-06 14:44 UTC, RoBarriosG commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +    public void showTag() {
Can this method be private?

2022-04-06 15:18 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +    public void showTag() {
listo!

2022-04-06 17:01 UTC, davburgos approved these changes

2022-04-06 17:57 UTC, francofusaro requested changes
Left some comments and suggestions 😄

2022-04-06 17:57 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/PaymentMethodDrawableItemMapper.kt
> +        val tag: Text? = if (value.displayInfo.isNotNull()) value.displayInfo.tag else null
This "If" is not necessary, in kotlin you can directly do:
`val tag = value.displayInfo?.tag`

2022-04-06 17:57 UTC, francofusaro commented on px-checkout/src/main/res/values/dimens.xml
> +    <dimen name="cc_text_size_12">12sp</dimen>
Can we use "px_..._text" dimensions instead of creating custom ones for this? I know those are in "sp" and px in "dp" but there is a reason for that and it's that if the user selects bigger texts on his phone this will probably look bad

2022-04-06 17:57 UTC, francofusaro commented on px-checkout/src/main/res/values/colors.xml
> +    <color name="andes_blue_ml_100">#1A4189E6</color>
We don't need to add this "andes" colors by ourself, we can access andes ones directly (see [line 199](https://github.com/mercadopago/px-android/pull/2693/files#diff-1855ce52304b47f03e7aa4fb5f0e7d453563d8dc6bf9f4e406b0a92079d8d2b0R199))

2022-04-06 17:57 UTC, francofusaro commented on px-checkout/src/main/res/values/styles.xml
> +    <style name="BackgroundCustomerCredits">
Can we change the styles naming convention to snake case? Like "background_custom_credits" and so on? 😄

2022-04-06 17:57 UTC, francofusaro commented on px-checkout/src/main/res/layout/px_cc_drawer_tag.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Missing new line 😅

2022-04-06 18:11 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/PaymentMethodDrawableItemMapper.kt
> +        val tag: Text? = if (value.displayInfo.isNotNull()) value.displayInfo.tag else null
adjusted

2022-04-06 18:12 UTC, samantaalbanez commented on px-checkout/src/main/res/drawable/px_cc_tag_background.xml
> +</shape>
adjusted

2022-04-06 18:14 UTC, cardosodiego commented on px-checkout/src/main/res/values/dimens.xml
> +    <dimen name="cc_text_size_12">12sp</dimen>
Hmm... that's a good point to know. Thanks for the information.

2022-04-06 18:15 UTC, samantaalbanez commented on px-checkout/src/main/res/values/dimens.xml
> +    <dimen name="cc_text_size_12">12sp</dimen>
adjusted

2022-04-06 18:18 UTC, samantaalbanez commented on px-checkout/src/main/res/values/styles.xml
> +    <style name="BackgroundCustomerCredits">
adjusted

2022-04-06 18:18 UTC, samantaalbanez commented on px-checkout/src/main/res/layout/px_cc_drawer_tag.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
adjusted

2022-04-06 18:31 UTC, samantaalbanez commented on px-checkout/src/main/res/values/colors.xml
> +    <color name="andes_blue_ml_100">#1A4189E6</color>
adjusted

2022-04-06 21:09 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +        text.setText(model.tag.getMessage());
adjusted

2022-04-07 13:31 UTC, francofusaro commented on px-checkout/src/main/res/layout-h610dp/px_fragment_consumer_credits_dynamic.xml
> +                layout="@layout/px_cc_drawer_meddium_tag"
can we fix this typo? it should be "medium" not "meddium" 😄

2022-04-07 14:09 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +        if(model.tag != null) {
space

2022-04-07 14:09 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +        text.setTypeface(text.getTypeface(), CardDrawerFont.from(model.tag.getWeight()).getStyle());
Wouldn't it be nice to have a default value in case the backend sends fruit?

2022-04-07 14:09 UTC, daniivillegas commented on px-checkout/src/main/res/layout-h610dp/px_fragment_consumer_credits_dynamic.xml
> +                app:layout_constraintEnd_toStartOf="@+id/tag_guideline"
Should be @id/tag_guideline

2022-04-07 14:09 UTC, daniivillegas commented on px-checkout/src/main/res/layout/px_cc_drawer_small_tag.xml
> +        tools:text="New tag larger for ellipsis" />
space

2022-04-07 14:09 UTC, daniivillegas commented on px-checkout/src/main/res/layout/px_cc_drawer_tag.xml
> +        tools:text="New tag larger for ellipsis" />
space

2022-04-07 14:09 UTC, daniivillegas commented on px-checkout/src/main/res/layout/px_consumer_credits_card_view_mini.xml
> +            tools:ignore="contentDescription"/>
why ignore?

2022-04-07 14:11 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +        if(model.tag != null) {
adjusted

2022-04-07 14:12 UTC, samantaalbanez commented on px-checkout/src/main/res/layout-h610dp/px_fragment_consumer_credits_dynamic.xml
> +                app:layout_constraintEnd_toStartOf="@+id/tag_guideline"
adjusted

2022-04-07 14:13 UTC, samantaalbanez commented on px-checkout/src/main/res/layout/px_cc_drawer_tag.xml
> +        tools:text="New tag larger for ellipsis" />
adjusted

2022-04-07 14:14 UTC, samantaalbanez commented on px-checkout/src/main/res/layout/px_consumer_credits_card_view_mini.xml
> +            tools:ignore="contentDescription"/>
adjusted

2022-04-07 14:19 UTC, RoBarriosG submitted a review, later dismissed

2022-04-07 14:20 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +    @Nullable public final Text tag;
Wait! the tag that you should use should come in the ExpressMetada DisplayInfo, let's maintain consistency with the other cards.

2022-04-07 14:31 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +    @Nullable public final Text tag;
oops, i missed this, that's true, we already have a tag [here](https://github.com/mercadopago/px-android/blob/master/px-services/src/main/java/com/mercadopago/android/px/model/one_tap/SliderDisplayInfo.kt#L14) for the other payment methods, we should use it instead of creating a new one

2022-04-07 14:41 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +    @Nullable public final Text tag;
adjusted

2022-04-07 16:13 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +        @NonNull final ConsumerCreditsMetadata metadata, @Nullable SliderDisplayInfo tag) {
Why do we call it tag and not sliderDisplayInfo?

2022-04-07 16:34 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +        text.setTypeface(text.getTypeface(), CardDrawerFont.from(tag.getWeight()).getStyle());
Here we should not be using the carddrawer font, we are not CardDrawer. Let's use `PxFont` and the helper we have.

`FontHelper.setFont()`

2022-04-07 16:37 UTC, jorGonzalez291292 commented on px-checkout/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/andes_font_semibold</item>
Is this font Family necessary? Since we are the source programmatically.

2022-04-07 18:24 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +        text.setTypeface(text.getTypeface(), CardDrawerFont.from(model.tag.getWeight()).getStyle());
adjusted

2022-04-07 18:27 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +        @NonNull final ConsumerCreditsMetadata metadata, @Nullable SliderDisplayInfo tag) {
adjusted

2022-04-07 18:28 UTC, samantaalbanez commented on px-checkout/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/andes_font_semibold</item>
adjusted

2022-04-07 18:28 UTC, samantaalbanez commented on px-checkout/src/main/res/values/styles.xml
> +        <item name="android:fontFamily">@font/andes_font_semibold</item>
adjusted

2022-04-07 19:45 UTC, daniivillegas commented on px-core/src/main/java/com/mercadopago/android/px/core/presentation/extensions/DrawableExt.kt
> +}
The color utilis should be in another file

2022-04-07 19:48 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +        sliderDisplayInfo = in.readParcelable(ConsumerCreditsMetadata.class.getClassLoader());
adjusted

2022-04-07 20:02 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +        text.setTypeface(text.getTypeface(), CardDrawerFont.from(tag.getWeight()).getStyle());
adjusted

2022-04-07 21:00 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +        text.setTypeface(text.getTypeface(), CardDrawerFont.from(tag.getWeight()).getStyle());
adjusted

2022-04-07 21:00 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +    @Nullable public final SliderDisplayInfo sliderDisplayInfo;
adjusted

2022-04-08 13:09 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +        this.tag = tag;
The tag field would put it inside ConsumerCreditsMetadata - DisplayInfo

2022-04-08 13:09 UTC, daniivillegas commented on px-core/src/main/java/com/mercadopago/android/px/core/presentation/extensions/ColorUtils.kt
> +package com.mercadopago.android.px.core.presentation.extensions
Create other package with name "utils" and put this object there

2022-04-08 13:09 UTC, daniivillegas commented on px-core/src/main/java/com/mercadopago/android/px/core/presentation/extensions/DrawableExt.kt
> +
Space

2022-04-08 13:09 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +    private void showTag(Text tag) {
Adds annotation @NonNull and final

2022-04-08 13:12 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +        this.tag = tag;
I don't agree with this, as ConsumerCreditsMetadata is the model that comes from backend, so it would be weird to have it there but it comes in another place

2022-04-08 13:16 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/ConsumerCreditsDrawableFragmentItem.java
> +        this.tag = tag;
In this case, this information is coming from outside the displayinfo node of consumer credits. 
For example, can you check here searching for "tag" a response from backend: 
https://run.mocky.io/v3/352ef5e5-b61c-46d3-a572-f8f5af57ec75

2022-04-08 13:47 UTC, cardosodiego commented on px-core/src/main/java/com/mercadopago/android/px/core/presentation/extensions/ColorUtils.kt
> +package com.mercadopago.android.px.core.presentation.extensions
listo!

2022-04-08 13:47 UTC, cardosodiego commented on px-core/src/main/java/com/mercadopago/android/px/core/presentation/extensions/DrawableExt.kt
> +
listo!

2022-04-08 13:47 UTC, cardosodiego commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/ConsumerCreditsFragment.java
> +    private void showTag(Text tag) {
listo!

2022-04-08 14:01 UTC, daniivillegas submitted a review, later dismissed

2022-04-08 15:27 UTC, jorGonzalez291292 commented on px-core/src/main/java/com/mercadopago/android/px/core/presentation/utils/ColorUtils.kt
> +    fun safeParcelColor(color: String?, defaultColor: Int) = runCatching {
`safeParcelColor` to `safeParseColor`

2022-04-08 15:36 UTC, cardosodiego commented on px-core/src/main/java/com/mercadopago/android/px/core/presentation/utils/ColorUtils.kt
> +    fun safeParcelColor(color: String?, defaultColor: Int) = runCatching {
listo!

2022-04-08 15:41 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/PaymentMethodDrawableItemMapper.kt
> +                isConsumerCredits -> ConsumerCreditsDrawableFragmentItem(parameters, consumerCredits, displayInfo?.tag)
did you analyze what we talked yesterday about sending "displayInfo?.tag" inside "parameters"? 😄

2022-04-08 16:28 UTC, daniivillegas approved these changes

2022-04-08 17:18 UTC, samantaalbanez commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/PaymentMethodDrawableItemMapper.kt
> +                isConsumerCredits -> ConsumerCreditsDrawableFragmentItem(parameters, consumerCredits, displayInfo?.tag)
As we talked about yesterday, it makes no sense to send the tag in parameters, as it is specific to consumer credits and parameters are used for other types of cards as well

2022-04-08 17:42 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/drawables/PaymentMethodDrawableItemMapper.kt
> +                isConsumerCredits -> ConsumerCreditsDrawableFragmentItem(parameters, consumerCredits, displayInfo?.tag)
oh i see, it's okay then, thanks!

2022-04-08 17:43 UTC, francofusaro approved these changes

2022-04-08 18:29 UTC, jorGonzalez291292 approved these changes

2022-04-08 18:31 UTC, merged