[Fix]: PXN-3579 - Handler error when customOptionId is invalid
mercadopago/px-android pull request #2696
Opened 2022-04-04 22:42 UTC by RoBarriosG

## Motivación y Contexto

Add runCatching to handle errors when calling `createPaymentResult` on `PaymentRepository`

## Descripción

For semovi flow the integrator was opening our congrats and in some cases the `customOptionId` has an invalid value, because the sharedPreference is returning null and by default the  `customOptionId` is empty

## Cómo probarlo

using the testApp launch a postPaymentFlow, then tap any button in order to show the congrats screen, then stop the flow using the debugger on `TransactionInfoFactory` line number 12 and update the customOptionId value to other value (for example : "test"), then let the flow continue.

## Screenshots

Error | Solution
-----|-----
 ![PXN_3579_error](https://user-images.githubusercontent.com/90635466/161643683-1f140f0c-456a-4109-9746-bff2a0e65f1c.gif) | ![PXN_3576_solution](https://user-images.githubusercontent.com/90635466/161641226-4afde8ec-3556-4021-b934-8758e866b933.gif)

## Tipo de cambio (para el release manager)
- [ ] Breaking change (Fix o feature que cambia una funcionalidad existente o rompe firmas)

- [ ] Mi cambio afecta a los integradores internos

## Compartir conocimiento

2022-04-05 12:35 UTC, samantaalbanez submitted a review, later dismissed

2022-04-05 17:35 UTC, samantaalbanez submitted a review, later dismissed

2022-04-05 18:56 UTC, cardosodiego approved these changes

2022-04-06 12:49 UTC, jorGonzalez291292 requested changes

2022-04-06 12:49 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/OneTapItemRepositoryImpl.kt
> +            ?: error("OneTapItem not found")
Watch out! This will end up showing the user on the error screen. We can't show you "OneTapItem not found"... it's out of context lol

2022-04-06 12:58 UTC, jorGonzalez291292 commented
From what I understand we are catching the error... but do we know why it happens? We have no way to avoid this inconsistency?
For the user it will continue to be a bad experience.

Doesn't it have to do with the double initialization that we fixed last time?

2022-04-06 14:04 UTC, RoBarriosG commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/OneTapItemRepositoryImpl.kt
> +            ?: error("OneTapItem not found")
Yes, you are right about it and that is what this PR is for, but the question is what do we show, since this also occurs in the normal flow only if it is being caught and it is returning the generic message of the exception

2022-04-06 14:31 UTC, RoBarriosG commented
> From what I understand we are catching the error... but do we know why it happens? We have no way to avoid this inconsistency? For the user it will continue to be a bad experience.
> 
> Doesn't it have to do with the double initialization that we fixed last time?

It has nothing to do with the double initialization, since it was blocking the flow before reaching that part and the version is not productive yet.

In the search the only thing that could be found is that it should be migrated to dataStorage if sharedPreference is used since sharedPreference uses synchronous processes in the main process and this may not end well in some cases. ie do not save or get a preference.

By default in some preferences we have that if it was not found an empty value is returned, which happens in the case of the customOptionId preference

2022-04-06 17:14 UTC, samantaalbanez approved these changes

2022-04-06 17:48 UTC, jorGonzalez291292 commented on CHANGELOG.md
> +* FIX - Crash when customOptionId is invalid
Wouldn't that be an improvement in how we handle errors? Since what we do does not solve the crash itself.

2022-04-06 18:42 UTC, RoBarriosG commented on CHANGELOG.md
> +* FIX - Crash when customOptionId is invalid
Done

2022-04-06 19:28 UTC, jorGonzalez291292 approved these changes

2022-04-06 19:38 UTC, merged