[Feature] Payment processor disambiguation
mercadopago/px-android pull request #2697
Opened 2022-04-05 13:44 UTC by jorGonzalez291292

## Motivación y Contexto
Start PX as a payment method selector and return the payment method ready to be used.

## Descripción
A new <ConfirmButton> is created to encapsulate the button's behavior.
In turn, a set of interfaces is established that define the expected behavior of the buttons that inherit it. SelectorConfirmButton is created to return a result without paying.
Logic is added to be used in case there is a PayButton processor or SelectorButton in case there is not.

2022-04-06 17:14 UTC, francofusaro requested changes
In general it's a really impressive change, lots of logic got decoupled and isolated, it will be good for future changes 💪 
Left some minor comments and some other suggestions, if you don't understand something we can chat it 😄

2022-04-11 18:59 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapFragment.java
> +        // Hacerlo en el método que configura los adapters
hahaha it was a reminder comment

2022-04-11 19:18 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/ConfirmButtonFragment.kt
> +            visibility = View.VISIBLE
In another PR (https://github.com/mercadopago/px-android/pull/2701), I added visible(), gone(), invisible() methods in core module. Maybe I'll update this later.

2022-04-11 19:19 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/ConfirmButtonFragment.kt
> +            visibility = View.INVISIBLE
In another PR (https://github.com/mercadopago/px-android/pull/2701), I added visible(), gone(), invisible() methods in core module. Maybe I'll update this later.

2022-04-11 19:38 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/ConfirmButtonFragment.kt
> +        uiError.actionMessage?.also {
`let` returns the value of the block... I think that is better idea use `apply` method.

2022-04-11 20:13 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/ConfirmButtonViewModel.kt
> +                track(PayButtonPressedEvent(viewTrackPath))
We are going to add new tracks for each case. This week we will be defining it.

2022-04-11 20:22 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/SelectorConfirmButtonFragment.kt
> +            buttonTextLiveData.nonNullObserve(viewLifecycleOwner) {
is true :O

2022-04-11 20:45 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonFragment.kt
> -            buttonTextLiveData.nonNullObserve(viewLifecycleOwner) { buttonConfig ->
updated

2022-04-11 20:54 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonViewModel.kt
> +                success = audioPlayer::play,
Playing the sound takes it out of the use case because from my point of view it is something that should be handled by the presentation layer. Maybe we can rename the use case.

2022-04-11 20:58 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/ConfirmButtonUiState.kt
> +internal open class UIProgress : ConfirmButtonUiState() {
You are right. I can move it to another file.

2022-04-11 21:15 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/ConfirmButtonFragment.kt
> +            visibility = View.INVISIBLE
I understand that, i was saying if we can use [this one](https://android.github.io/android-ktx/core-ktx/androidx.view/android.view.-view/is-visible.html) that already comes on the core ktx. We added this in our px core as an api implementation so we can access it from where we use the core 🤔

2022-04-12 12:49 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/ConfirmButtonFragment.kt
> +            visibility = View.INVISIBLE
I don't know if I understood you correctly haha... but why change it now to isVisible=true if we already have new methods in the core that solve this?

2022-04-12 13:02 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/ConfirmButtonFragment.kt
> +            visibility = View.INVISIBLE
The point is that we already have methods for that in the core 😂 those that we take from core-ktx. I remember that Cami [told me to use them](https://github.com/mercadopago/px-android/pull/2596#discussion_r753418934) instead of creating new ones when i was developing px-core

2022-04-12 13:42 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/security_code/SecurityCodeFragment.kt
> -        } ?: payButtonFragment.disable()
Not anymore, it is configured when the configuration of the flow arrives.

2022-04-12 13:55 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/confirm_button/ConfirmButtonFragment.kt
> +            visibility = View.INVISIBLE
I think that methods are cleaner and more readable than assigning booleans. But let's discuss it...

2022-04-12 15:12 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonViewModel.kt
> +                success = audioPlayer::play,
Rename use-case to `SelectPaymentSoundUseCase`

2022-04-13 13:30 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/offline_methods/OfflineMethodsViewModel.kt
> +    private val fetchMutableLiveData = MutableLiveData<OfflineMethods.Model>()
I would name this "offlineMethodsModelMutableLiveData" or "modelMutableLiveData" (similar to the other, fetch makes me think that if i set it, it's gonna fetch something)

2022-04-13 13:52 UTC, francofusaro approved these changes
Just added a minor comment 🥳

2022-04-13 15:30 UTC, jorGonzalez291292 commented
Ready @francofusaro

2022-04-13 16:18 UTC, merged