[Feature] Added support to debin on in_process screen
mercadopago/px-android pull request #2701
Opened 2022-04-08 12:55 UTC by jorGonzalez291292

## Motivación y Contexto
Debin support

## Descripción
Debin supports the status_detail `pending_provider_response`, so you need to display an `in_process` screen showing the payment method.

## Screenshots
Figma:

<img width="257" alt="Captura de Pantalla 2022-04-08 a la(s) 09 47 19" src="https://user-images.githubusercontent.com/50373979/162438449-d3d41213-5fea-4468-84de-4b339cd05455.png">

Result:

![Screenshot_20220407-171518_MP Android SDK Samples](https://user-images.githubusercontent.com/50373979/162438884-dfeb12ac-d9fb-4d90-a619-10425c5645cd.jpg)

2022-04-08 12:59 UTC, jorGonzalez291292 commented
Translations are missing

2022-04-08 16:21 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultActivity.java
> +        if (remediesFragment == null || payButtonFragment == null) {
in the nested if, we already check for null. we can remove this, right?

2022-04-08 16:21 UTC, daniivillegas commented on px-core/src/main/java/com/mercadopago/android/px/core/presentation/extensions/ViewExt.kt
> +}
💯

2022-04-08 16:21 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +            return null;
is necessary return null in this block?

2022-04-08 16:21 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +            return null;
idem

2022-04-08 16:23 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +            return null;
Yes, the lambda asks for it because it is JAVA.

2022-04-08 16:23 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +            return null;
Yes, the lambda asks for it because it is JAVA.

2022-04-08 16:27 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +            return null;
:(

2022-04-08 16:27 UTC, daniivillegas commented
fixed lint :P

2022-04-08 16:28 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +        paymentResultViewModel = factory.createPaymentStatusWithProps(props.status, props.statusDetail, props);
we're passing props and their fields, couldn't we just pass props and call the fields from the method?

2022-04-08 16:32 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/PaymentResultActivity.java
> +        if (remediesFragment == null || payButtonFragment == null) {
Just take out the main yes, the rest doesn't touch it haha

2022-04-08 18:21 UTC, jorGonzalez291292 commented on px-checkout/src/main/res/values/strings.xml
> +    <string name="px_pending_body_detail_bank_transfer">En un máximo de 10 minutos podrás ver la confirmación en la sección Actividad.</string>
Not because debin is not in MLB.

2022-04-08 18:27 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/props/BodyErrorProps.java
> +
done

2022-04-08 18:36 UTC, daniivillegas approved these changes

2022-04-11 14:06 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +            return null;
instead of null, return Unit.INSTANCE

2022-04-11 14:06 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +            return null;
instead of null, return Unit.INSTANCE

2022-04-12 14:32 UTC, samantaalbanez submitted a review, later dismissed

2022-04-12 14:33 UTC, samantaalbanez reviewed
Changelog file is missing

2022-04-12 16:22 UTC, samantaalbanez submitted a review, later dismissed

2022-04-19 15:45 UTC, daniivillegas submitted a review, later dismissed

2022-04-19 16:13 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +        if (paymentResultViewModel.hasBodyTitle()) {
Can we do paymentResultViewModel.getBodyTitle() directly? Since it already check if it's 0

2022-04-19 16:13 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/props/BodyErrorProps.java
> +    public final List<PaymentResultMethod.Model> methodModels;
Maybe we can name this "paymentResultMethodModels" to improve readability, since "methodModels" sounds much generic, what do you think?

2022-04-19 16:13 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/props/PaymentResultBodyProps.java
> +    public final List<PaymentResultMethod.Model> methodModels;
Same as the other

2022-04-19 16:13 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/props/PaymentResultBodyProps.java
> +        public List<PaymentResultMethod.Model> methodModels = Collections.emptyList();
Same as the other

2022-04-19 16:13 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/viewmodel/PaymentResultLegacyViewModel.java
> +    public final List<PaymentResultMethod.Model> methodModels;
Same as the other

2022-04-19 16:13 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultBody.java
> +        public final List<PaymentResultMethod.Model> methodModels;
Same as the other

2022-04-19 16:13 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +        final boolean isPaymentMethodsValid = paymentResultViewModel.requiresShowPaymentMethods() &&
What does "isPaymentMethodsValid" mean? It looks more like it's if it should show them or not, maybe we can rename this to "shouldShowPaymentMethods" or something like that, what do you think?

2022-04-19 16:17 UTC, francofusaro requested changes

2022-04-19 16:17 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/components/BodyError.java
> +        final boolean isPaymentMethodsValid = paymentResultViewModel.requiresShowPaymentMethods() &&
What does "isPaymentMethodsValid" mean? It looks more like it's if it should show them or not, maybe we can rename this to "shouldShowPaymentMethods" or something like that, what do you think?

2022-04-19 16:17 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/viewmodel/PaymentResultViewModel.java
> +    public boolean requiresShowPaymentMethods() {
Maybe we can rename this to "shouldShowPaymentMethods", what do you think?

2022-04-19 16:17 UTC, francofusaro commented on px-services/src/main/java/com/mercadopago/android/px/model/Payment.java
> +        public static final String STATUS_DETAIL_PENDING_PENDING_PROVIDER_RESPONSE = "pending_provider_response";
"PENDING" word is duplicated 😄

2022-04-19 17:57 UTC, francofusaro approved these changes

2022-04-19 19:18 UTC, daniivillegas submitted a review, later dismissed

2022-04-19 21:16 UTC, francofusaro approved these changes

2022-04-21 15:15 UTC, daniivillegas submitted a review, later dismissed

2022-04-22 14:59 UTC, francofusaro approved these changes

2022-04-28 20:17 UTC, francofusaro approved these changes

2022-04-28 20:23 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CongratsRepositoryImpl.kt
> +            else -> getCongratsResponse(payment, paymentResult).apply { paymentRewardCache[paymentId] = this }
also en vez de apply no juega?

2022-04-28 20:28 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CongratsRepositoryImpl.kt
> +            paymentRewardCache.containsKey(paymentId) -> paymentRewardCache[paymentId]!!
paymentRewardCache is a legacy name, as we are touching all of this, we not name it congratsCache?

2022-04-28 20:34 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/props/BodyErrorProps.java
> +        public Builder setPaymentResultMethodModels(final List<PaymentResultMethod.Model> paymentResultMethodModels) {
@NonNull?

2022-04-28 20:34 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_result/props/PaymentResultBodyProps.java
> +        public Builder setPaymentResultMethodModels(final List<PaymentResultMethod.Model> paymentResultMethodModels) {
@NonNull?

2022-04-28 20:35 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/util/StatusHelper.kt
> +    private fun isGenericInProcess(payment: IPaymentDescriptor) = with(payment) {
Is this method still used? It's private

2022-04-28 20:36 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/view/PaymentResultBody.java
> +        public final List<PaymentResultMethod.Model> paymentResultMethodModels;
Maybe we should add a getter instead of making public the property

2022-04-28 20:46 UTC, guchito9 approved these changes

2022-04-28 20:56 UTC, daniivillegas commented
fix lint and test

2022-04-29 14:41 UTC, guchito9 approved these changes

2022-04-29 14:42 UTC, francofusaro approved these changes

2022-04-29 14:51 UTC, merged