[Feature] Bank account callback
mercadopago/px-android pull request #2709
Opened 2022-04-13 19:58 UTC by daniivillegas

## Motivación y Contexto

## Descripción

## Cómo probarlo

## Screenshots

## Tipo de cambio (para el release manager)
- [ ] Breaking change (Fix o feature que cambia una funcionalidad existente o rompe firmas)

- [ ] Mi cambio afecta a los integradores internos

## Compartir conocimiento

2022-04-26 18:14 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +        checkoutHelper.init(payerPaymentMethodKey)
I think that everything that is the helper and the internal logic of the checkout factory can be inside the initRequestBodyMapper or inject another mapper that contains this logic.

2022-04-26 18:16 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +            is Response.Failure -> FindCardResult(false, response)
Opinion: If you change the order of the arguments you can put a default value to the boolean

2022-04-26 18:39 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +            is Response.Failure -> FindCardResult(false, response)
In what case would the order of the arguments change?

2022-04-26 19:12 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/Checkout.java
> +import android.net.Uri;
This is used?

2022-04-26 19:14 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +            is Response.Failure -> FindCardResult(false, response)
In the case that I put the comment.
`FindCardResult(false, response)` -> `FindCardResult(response, false)` -> `FindCardResult(response)`

2022-04-26 19:19 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java
> +        checkoutWithNewCardUseCase.execute(new PayerPaymentMethodKey(cardId, PaymentTypes.CREDIT_CARD),
Are we always going to add a credit card? What happened to the debits? :P

2022-04-26 19:19 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java
> +        checkoutWithNewCardUseCase.execute(new PayerPaymentMethodKey(cardId, PaymentTypes.CREDIT_CARD),
This name never changed. It should be more generic.

2022-04-26 19:51 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java
> +        checkoutWithNewCardUseCase.execute(new PayerPaymentMethodKey(cardId, PaymentTypes.CREDIT_CARD),
in this case we don't care if it's credit or debit, we could send a null, what do you say?

2022-04-26 20:22 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapFragment.java
> +        final DeepLinkResolver deepLinkResolver = MapperProvider.INSTANCE.getUriToDeepLinkWrapperMapper().map(uri);
1. All of this would lead to the presenter.
2. All the mapper logic with the decision making of which flow to go (`onBankAccountAdded` or `onDefault`) would do it with a simple `when` in the presenter.

2022-04-26 20:25 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java
> +        checkoutWithNewCardUseCase.execute(new PayerPaymentMethodKey(cardId, PaymentTypes.CREDIT_CARD),
It is used when we add a bank account as well.

2022-04-27 13:48 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java
> +        checkoutWithNewCardUseCase.execute(new PayerPaymentMethodKey(cardId, PaymentTypes.CREDIT_CARD),
I think that in order not to generate confusion and/or send parameters that are not going to be used, it is better to separate the case of adding a card or a bank account as separate use cases that receive different arguments.

2022-04-27 14:03 UTC, jorGonzalez291292 commented
@daniivillegas Why we remove MaterialCardView?

2022-04-27 14:56 UTC, francofusaro requested changes

2022-04-27 14:56 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodPresenter.java
> +        getView().configureListenerHandler(new AddNewCard.Actions() {
ListenerHandler sounds weird 🤔 and it also looks like this can be simplified

2022-04-27 14:56 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/util/SecurityUtil.kt
> +}
missing new line

2022-04-27 14:56 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/model/internal/CheckoutFeatures.kt
> +        const val NEW_PAYMENT_METHOD_STAGE = "v1"
Can this be "NEW_PAYMENT_METHOD_VERSION"? To keep the convention that we use for the others

2022-04-27 14:56 UTC, francofusaro commented on px-checkout/src/main/res/layout/px_other_payment_method_card_view_large_low_res.xml
> +</androidx.cardview.widget.CardView>
missing new line

2022-04-27 14:56 UTC, francofusaro commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/CheckoutResponse.kt
> +    val retryNeeded: Retry? = null
Can we name this "retry"? So we avoid having retryNeeded.isNeeded 😄

2022-04-27 18:02 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/checkout/CheckoutPresenter.java
> +        checkoutWithNewCardUseCase.execute(new PayerPaymentMethodKey(cardId, PaymentTypes.CREDIT_CARD),
fixed

2022-04-27 18:03 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapFragment.java
> +            presenter.onCardResult();
onCardAddedResult messie

2022-04-27 18:07 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapFragment.java
> +            final String paymentType = data.getStringExtra(CardForm.RESULT_PAYMENT_TYPE_KEY);
field not required

2022-04-27 18:07 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
> +        } ?: also {
fixed with let :P

2022-04-27 18:11 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/InitRequestBodyMapper.kt
> +    fun mapForBankTransfer(paymentSettingRepository: PaymentSettingRepository, bankAccountId: String?): InitRequestBody {
done

2022-04-27 18:12 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/CheckoutBankTransfer.kt
> +        initRequestBodyMapper.mapForBankTransfer(
done

2022-04-27 18:16 UTC, daniivillegas commented on px-checkout/src/main/res/layout/px_other_payment_method_card_view_large_low_res.xml
> +</androidx.cardview.widget.CardView>
done

2022-04-27 18:16 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/util/SecurityUtil.kt
> +}
done

2022-04-27 18:18 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +                    "Parent fragment must implement " + TAG
done

2022-04-27 18:19 UTC, daniivillegas commented
@jorGonzalez291292 we remove material card view because in the version we have in the whitelist, we need to set a theme and it doesn't take the background and the border

2022-04-27 18:26 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodListenerHandler.kt
> +    fun getListenerForAddNewCard(newCardMetadata: NewCardMetadata) = when {
execute the listener, would it be a handler?

2022-04-27 19:13 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +            Logger.debug(TAG, e);
done

2022-04-27 20:44 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodPresenter.java
> +                TrackWrapper.BASE_PATH + "/post_payment_deep_link",
And this Path??

`"/post_payment_deep_link"`

2022-04-27 20:44 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/CheckoutStrategy.kt
> +internal interface CheckoutStrategy {
Esto se sigue usando?

2022-04-27 20:55 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +    private suspend fun doCheckout(cardId: String?, bankAccountId: String?): ResponseCallback<CheckoutResponse> {
`doCheckout(cardId: String? = null, bankAccountId: String? = null)`

2022-04-27 20:55 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +    override suspend fun checkout() = doCheckout(null, null)
use default arguments.

2022-04-27 20:55 UTC, jorGonzalez291292 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +        var findCardResult = checkoutAndFindCard(cardId, bankAccountId)
change name to `checkoutAndFindPaymentMethod` or any other name more generic.

2022-04-27 21:31 UTC, daniivillegas commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodPresenter.java
> +                TrackWrapper.BASE_PATH + "/post_payment_deep_link",
wtf jajajaja.

/bank_account_added/?

2022-04-27 21:41 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +    data class FindCardResult(
```suggestion
    data class FindPaymentMethodResult(
```

2022-04-27 21:41 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/CheckoutRepositoryImpl.kt
> +    data class FindCardResult(
this should be FindPaymentMethodResult

2022-04-27 21:41 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/base/BasePresenter.kt
> +abstract class BasePresenter<V : MvpView>(protected val tracker: MPTracker) {
👀

2022-04-27 21:46 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodFragment.java
> +        }
can we use [check](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/check.html) instead of doing an if/else?

2022-04-27 21:47 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/add_new_card/OtherPaymentMethodPresenter.kt
> +        }
extra spaces at the start

2022-05-04 19:00 UTC, jorGonzalez291292 approved these changes

2022-05-04 19:13 UTC, francofusaro approved these changes

2022-05-04 19:13 UTC, merged