[Feature] Custom wordings
mercadopago/px-android pull request #2717
Opened 2022-04-22 13:54 UTC by jorGonzalez291292

## Motivación y Contexto
It is necessary to have more contextual texts about what things can or cannot be done with each payment method.

## Descripción
Models that help us to customize the wordings for the modals of the behaviors are added to the PX signature as a payment method selector. These are applied through rules defined by the integrator.

[Documentation](https://docs.google.com/document/d/15Rlj5hJqfsZR49_wsipT41XRYUmfmRHQBmn70EazjgU/edit?usp=sharing)

2022-04-27 14:38 UTC, RoBarriosG commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/di/MapperProvider.kt
> +import com.mercadopago.android.px.internal.mappers.*
minor comment, remove wildcard imports

2022-04-27 14:48 UTC, RoBarriosG commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/PaymentMethodFragment.java
> +            startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(deepLink)));
Use MercadoPagoUtil.getIntent(deepLink)

2022-04-27 14:50 UTC, RoBarriosG commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/InitRequestBodyMapper.kt
> +import com.mercadopago.android.px.model.internal.*
remove wildcard imports

2022-04-27 15:14 UTC, francofusaro requested changes

2022-04-27 15:14 UTC, francofusaro commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/slider/PaymentMethodFragment.java
> +        if(genericDialogAction instanceof GenericDialogAction.DeepLinkAction) {
missing space between if and "("

2022-04-27 15:14 UTC, francofusaro commented on px-services/build.gradle
> +            buildConfigField "String", "API_ENVIRONMENT_NEW", "$Environment.GAMMA"
Watch out! 😛

2022-04-27 15:14 UTC, francofusaro commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/InitRequestBody.kt
> +    @SerializedName("payment_method_behaviour")
Can this be in plural? 😄

2022-04-27 15:14 UTC, francofusaro commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/Application.kt
> +    @SerializedName("behaviour")
Can this be in plural? 😄

2022-04-27 15:14 UTC, francofusaro commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/PaymentMethodBehaviourDM.kt
> +    @SerializedName("payment_types_rules")
Can "types" be in singular? 😄

2022-04-27 15:16 UTC, jorGonzalez291292 commented
@francofusaro They have to change the backend, for the moment to test I use the serializationName(""). When the changes are updated I'll update it.

2022-05-02 15:38 UTC, francofusaro approved these changes

2022-05-02 15:41 UTC, daniivillegas approved these changes

2022-05-02 19:09 UTC, guchito9 commented on CHANGELOG.md
> +* FEATURE - Custom behaviour
It lacks some context, custom behaviour for what?

2022-05-02 19:10 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/configuration/AdvancedConfiguration.java
> +        public Builder setPaymentMethodBehaviours(final List<PaymentMethodBehaviour> paymentMethodBehaviours) {
@NonNull?

2022-05-02 19:13 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/disable_payment_method/DisabledPaymentMethodDetailDialog.java
> +import java.security.MessageDigest;
👀

2022-05-02 19:15 UTC, guchito9 commented on px-checkout/src/main/java/com/mercadopago/android/px/internal/features/generic_modal/FromModalToGenericDialogItem.kt
> +data class FromModalToGenericDialogItemParams(
I think it's better to simply name the class as Params but declare it as inner class of the mapper

2022-05-02 19:22 UTC, guchito9 commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/Application.kt
> +    val behaviours: Map<String, CheckoutBehaviour>
Should this be nullable or will come always from backend?

2022-05-02 19:34 UTC, jorGonzalez291292 commented on px-services/src/main/java/com/mercadopago/android/px/model/internal/Application.kt
> +    val behaviours: Map<String, CheckoutBehaviour>
This arrives empty from backend.

2022-05-02 19:44 UTC, guchito9 commented on gradle/deploy_base.gradle
> +                    password = "n6J3E|_dt2_C18LoFmlv5rT||"
👀

2022-05-02 19:56 UTC, guchito9 approved these changes

2022-05-03 13:07 UTC, merged